version: "3.8"

services:
  frontend:
    build: ./mini_trello_fe
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./mini_trello_be
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
